name: 'Setup Dependencies'
description: 'Install platform-specific dependencies for building mlvg'
inputs:
  platform:
    description: 'Platform to setup (linux, windows, macos)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Install dependencies (Linux)
      if: inputs.platform == 'linux'
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake git
        sudo apt-get install -y libsdl2-dev libsdl2-2.0-0
        sudo apt-get install -y libgl1-mesa-dev libglu1-mesa-dev
        sudo apt-get install -y pkg-config
    
    - name: Install dependencies (Windows)
      if: inputs.platform == 'windows'
      shell: pwsh
      run: |
        mkdir SDL
        cd SDL
        Invoke-WebRequest -Uri "https://github.com/libsdl-org/SDL/releases/download/release-2.28.5/SDL2-devel-2.28.5-VC.zip" -OutFile "sdl2.zip"
        Expand-Archive -Path "sdl2.zip" -DestinationPath "."
        Move-Item -Path "SDL2-2.28.5\*" -Destination "." -Force
        cd ..
    
    # TODO: SDL2. mlvg won't find homebrew's
    - name: Install dependencies (macOS)
      if: inputs.platform == 'macos'
      shell: bash
      run: |
        brew install cmake
