name: 'Build MLVG'
description: 'Build the main mlvg project'
inputs:
  platform:
    description: 'Platform to build for (linux, windows, macos)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Build mlvg (Linux)
      if: inputs.platform == 'linux'
      shell: bash
      run: |
        mkdir build && cd build
        cmake -DBUILD_CLAP_EXAMPLE=ON -DBUILD_SDL2_APP=OFF -DBUILD_TESTS=ON ..
        make -j$(nproc)
        cmake --build . --target tests --verbose
    - name: Build mlvg (Windows)
      if: inputs.platform == 'windows'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x64
      shell: pwsh
      run: |
        mkdir build
        cd build
        cmake -G "Ninja" -DCMAKE_BUILD_TYPE=Release -DBUILD_CLAP_EXAMPLE=ON -DBUILD_SDL2_APP=OFF -DBUILD_TESTS=ON -DSDL2_INCLUDE_DIRS="../SDL/include" -DSDL2_LIBRARIES_DIR="../SDL/lib/x64" ..
        cmake --build . --verbose
        cmake --build . --target tests --verbose
    - name: Build mlvg (macOS)
      if: inputs.platform == 'macos'
      shell: bash
      run: |
        mkdir build && cd build
        cmake -DBUILD_CLAP_EXAMPLE=ON -DBUILD_SDL2_APP=OFF -DBUILD_TESTS=ON ..
        make -j$(sysctl -n hw.ncpu)
        cmake --build . --target tests --verbose
