name: 'Test Madronalib'
description: 'Run madronalib test suite from existing build'
inputs:
  platform:
    description: 'Platform to test on (linux, windows, macos)'
    required: true
runs:
  using: 'composite'
  steps:
    # Test madronalib on Linux - checks both bin/ and root locations for test executable
    - name: Test madronalib (Linux)
      if: inputs.platform == 'linux'
      shell: bash
      run: |
        cd madronalib/build
        if [ -f "./bin/tests" ]; then
          ./bin/tests
        elif [ -f "./tests" ]; then
          ./tests
        else
          echo "Error: Test executable not found in madronalib/build/"
          exit 1
        fi
    
    # Test madronalib on Windows - checks both Release/ and bin/ locations for test executable
    - name: Test madronalib (Windows)
      if: inputs.platform == 'windows'
      shell: pwsh
      run: |
        cd madronalib/build
        if (Test-Path "./Release/tests.exe") {
          ./Release/tests.exe
        } elseif (Test-Path "./bin/tests.exe") {
          ./bin/tests.exe
        } else {
          Write-Error "Error: Test executable not found in madronalib/build/"
          exit 1
        }
    
    # Test madronalib on macOS - checks both bin/ and root locations for test executable
    - name: Test madronalib (macOS)
      if: inputs.platform == 'macos'
      shell: bash
      run: |
        cd madronalib/build
        if [ -f "./bin/tests" ]; then
          ./bin/tests
        elif [ -f "./tests" ]; then
          ./tests
        else
          echo "Error: Test executable not found in madronalib/build/"
          exit 1
        fi
