name: 'Build Madronalib'
description: 'Build and install madronalib dependency'
inputs:
  platform:
    description: 'Platform to build for (linux, windows, macos)'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Build madronalib (Linux)
      if: inputs.platform == 'linux'
      shell: bash
      run: |
        git clone -b debug-linux-build-errors-20250822 https://github.com/johnmatter/madronalib.git
        cd madronalib
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DLINUX_ASOUND=ON -DBUILD_TESTS=ON ..
        make -j$(nproc)
        cmake --build . --target tests --verbose
        sudo make install
    - name: Build madronalib (Windows)
      if: inputs.platform == 'windows'
      shell: pwsh
      run: |
        git clone -b debug-windows-build-errors-20250821 https://github.com/johnmatter/madronalib.git
        cd madronalib
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
        cmake --build . --config Release
        cmake --build . --config Release --target tests --verbose
        echo "Installing madronalib to: %USERPROFILE%\madronalib"
        cmake --install . --prefix "%USERPROFILE%\madronalib"
        echo "Installation complete. Checking what was installed:"
        dir "%USERPROFILE%\madronalib" /s
    - name: Build madronalib (macOS)
      if: inputs.platform == 'macos'
      shell: bash
      run: |
        git clone -b debug-windows-build-errors-20250821 https://github.com/johnmatter/madronalib.git
        cd madronalib
        mkdir build && cd build
        cmake -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON ..
        make -j$(sysctl -n hw.ncpu)
        cmake --build . --target tests --verbose
        sudo make install
